#数据库配置
database:
  type: mysql
  host: 192.168.10.23
  port: 3306
  username: test
  password: RxTnAppSbsRc4jpJ
  database: test

  fieldSync: true
  tablePrefix:

redis:
  addr: 127.0.0.1:6379
  password:
  db:


#协议配置
protocol:
  dslDir: ./data/dsl/

#默认链路(监听-解析-推送)配置
link:
  - model: test
    subscribe:
      type: mqtt
      addr: 192.168.10.23:1883
      subscribe: server
      connectTimeout: 30s
      clientID: "server"
    frame:
    protocol: dlt645
    publish:
      type: mqtt
      addr: 192.168.10.23:1883
      publish: api
      param:
      clientID: publish


